// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGeneration = `-- name: GetGeneration :one
SELECT id, source_url, site_profile, status, variations, created_at
FROM generations
WHERE id = $1
`

func (q *Queries) GetGeneration(ctx context.Context, id pgtype.UUID) (Generation, error) {
	row := q.db.QueryRow(ctx, getGeneration, id)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SiteProfile,
		&i.Status,
		&i.Variations,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGeneration = `-- name: UpsertGeneration :exec
INSERT INTO generations (id, source_url, site_profile, status, variations, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    source_url   = EXCLUDED.source_url,
    site_profile = EXCLUDED.site_profile,
    status       = EXCLUDED.status,
    variations   = EXCLUDED.variations
`

type UpsertGenerationParams struct {
	ID          pgtype.UUID        `json:"id"`
	SourceUrl   string             `json:"source_url"`
	SiteProfile []byte             `json:"site_profile"`
	Status      string             `json:"status"`
	Variations  []byte             `json:"variations"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Creates a generation, or overwrites every column but created_at if one
// already exists at this id — matching domain.GenerationRepo.Save's own
// "creates or overwrites" contract. created_at is deliberately excluded
// from the update so a later terminal-state save (e.g. streaming ->
// completed) doesn't reset when the record was first created.
func (q *Queries) UpsertGeneration(ctx context.Context, arg UpsertGenerationParams) error {
	_, err := q.db.Exec(ctx, upsertGeneration,
		arg.ID,
		arg.SourceUrl,
		arg.SiteProfile,
		arg.Status,
		arg.Variations,
		arg.CreatedAt,
	)
	return err
}
