// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Generation struct {
	ID          pgtype.UUID        `json:"id"`
	SourceUrl   string             `json:"source_url"`
	SiteProfile []byte             `json:"site_profile"`
	Status      string             `json:"status"`
	Variations  []byte             `json:"variations"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LlmCall struct {
	ID               pgtype.UUID        `json:"id"`
	GenerationID     pgtype.UUID        `json:"generation_id"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	Strategy         pgtype.Text        `json:"strategy"`
	PromptTokens     int32              `json:"prompt_tokens"`
	CompletionTokens int32              `json:"completion_tokens"`
	LatencyMs        int32              `json:"latency_ms"`
	CostUsd          pgtype.Numeric     `json:"cost_usd"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
