// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetGeneration(ctx context.Context, id pgtype.UUID) (Generation, error)
	// Creates a generation, or overwrites every column but created_at if one
	// already exists at this id — matching domain.GenerationRepo.Save's own
	// "creates or overwrites" contract. created_at is deliberately excluded
	// from the update so a later terminal-state save (e.g. streaming ->
	// completed) doesn't reset when the record was first created.
	UpsertGeneration(ctx context.Context, arg UpsertGenerationParams) error
}

var _ Querier = (*Queries)(nil)
