// Code generated by MockGen. DO NOT EDIT.
// Source: analyze.go
//
// Generated by this command:
//
//	mockgen -source=analyze.go -destination=../../../test/mocks/httpapi/analyzer_mock.go -package=mockhttpapi
//

// Package mockhttpapi is a generated GoMock package.
package mockhttpapi

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodvieira/pricing-optimizer-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockanalyzer is a mock of analyzer interface.
type Mockanalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockanalyzerMockRecorder
	isgomock struct{}
}

// MockanalyzerMockRecorder is the mock recorder for Mockanalyzer.
type MockanalyzerMockRecorder struct {
	mock *Mockanalyzer
}

// NewMockanalyzer creates a new mock instance.
func NewMockanalyzer(ctrl *gomock.Controller) *Mockanalyzer {
	mock := &Mockanalyzer{ctrl: ctrl}
	mock.recorder = &MockanalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockanalyzer) EXPECT() *MockanalyzerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *Mockanalyzer) Execute(ctx context.Context, rawURL string) (*domain.SiteProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, rawURL)
	ret0, _ := ret[0].(*domain.SiteProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockanalyzerMockRecorder) Execute(ctx, rawURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*Mockanalyzer)(nil).Execute), ctx, rawURL)
}
