// Code generated by MockGen. DO NOT EDIT.
// Source: export.go
//
// Generated by this command:
//
//	mockgen -source=export.go -destination=../../../test/mocks/httpapi/exporter_mock.go -package=mockhttpapi
//

// Package mockhttpapi is a generated GoMock package.
package mockhttpapi

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodvieira/pricing-optimizer-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockexporter is a mock of exporter interface.
type Mockexporter struct {
	ctrl     *gomock.Controller
	recorder *MockexporterMockRecorder
	isgomock struct{}
}

// MockexporterMockRecorder is the mock recorder for Mockexporter.
type MockexporterMockRecorder struct {
	mock *Mockexporter
}

// NewMockexporter creates a new mock instance.
func NewMockexporter(ctrl *gomock.Controller) *Mockexporter {
	mock := &Mockexporter{ctrl: ctrl}
	mock.recorder = &MockexporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockexporter) EXPECT() *MockexporterMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *Mockexporter) Execute(ctx context.Context, in domain.ExportVariationInput) (*domain.ExportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*domain.ExportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockexporterMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*Mockexporter)(nil).Execute), ctx, in)
}
