// Code generated by MockGen. DO NOT EDIT.
// Source: get_generation.go
//
// Generated by this command:
//
//	mockgen -source=get_generation.go -destination=../../../test/mocks/httpapi/generation_getter_mock.go -package=mockhttpapi
//

// Package mockhttpapi is a generated GoMock package.
package mockhttpapi

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodvieira/pricing-optimizer-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockgenerationGetter is a mock of generationGetter interface.
type MockgenerationGetter struct {
	ctrl     *gomock.Controller
	recorder *MockgenerationGetterMockRecorder
	isgomock struct{}
}

// MockgenerationGetterMockRecorder is the mock recorder for MockgenerationGetter.
type MockgenerationGetterMockRecorder struct {
	mock *MockgenerationGetter
}

// NewMockgenerationGetter creates a new mock instance.
func NewMockgenerationGetter(ctrl *gomock.Controller) *MockgenerationGetter {
	mock := &MockgenerationGetter{ctrl: ctrl}
	mock.recorder = &MockgenerationGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgenerationGetter) EXPECT() *MockgenerationGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockgenerationGetter) Get(ctx context.Context, id string) (*domain.Generation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Generation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockgenerationGetterMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockgenerationGetter)(nil).Get), ctx, id)
}
