// Code generated by MockGen. DO NOT EDIT.
// Source: idempotency.go
//
// Generated by this command:
//
//	mockgen -source=idempotency.go -destination=../../../test/mocks/httpapi/idempotency_store_mock.go -package=mockhttpapi
//

// Package mockhttpapi is a generated GoMock package.
package mockhttpapi

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockidempotencyStore is a mock of idempotencyStore interface.
type MockidempotencyStore struct {
	ctrl     *gomock.Controller
	recorder *MockidempotencyStoreMockRecorder
	isgomock struct{}
}

// MockidempotencyStoreMockRecorder is the mock recorder for MockidempotencyStore.
type MockidempotencyStoreMockRecorder struct {
	mock *MockidempotencyStore
}

// NewMockidempotencyStore creates a new mock instance.
func NewMockidempotencyStore(ctrl *gomock.Controller) *MockidempotencyStore {
	mock := &MockidempotencyStore{ctrl: ctrl}
	mock.recorder = &MockidempotencyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidempotencyStore) EXPECT() *MockidempotencyStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockidempotencyStore) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockidempotencyStoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockidempotencyStore)(nil).Get), ctx, key)
}

// Release mocks base method.
func (m *MockidempotencyStore) Release(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockidempotencyStoreMockRecorder) Release(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockidempotencyStore)(nil).Release), ctx, key)
}

// Reserve mocks base method.
func (m *MockidempotencyStore) Reserve(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockidempotencyStoreMockRecorder) Reserve(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockidempotencyStore)(nil).Reserve), ctx, key)
}

// Save mocks base method.
func (m *MockidempotencyStore) Save(ctx context.Context, key, generationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, key, generationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockidempotencyStoreMockRecorder) Save(ctx, key, generationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockidempotencyStore)(nil).Save), ctx, key, generationID)
}
