// Code generated by MockGen. DO NOT EDIT.
// Source: ratelimit.go
//
// Generated by this command:
//
//	mockgen -source=ratelimit.go -destination=../../../test/mocks/httpapi/rate_limiter_mock.go -package=mockhttpapi
//

// Package mockhttpapi is a generated GoMock package.
package mockhttpapi

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockrateLimiter is a mock of rateLimiter interface.
type MockrateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockrateLimiterMockRecorder
	isgomock struct{}
}

// MockrateLimiterMockRecorder is the mock recorder for MockrateLimiter.
type MockrateLimiterMockRecorder struct {
	mock *MockrateLimiter
}

// NewMockrateLimiter creates a new mock instance.
func NewMockrateLimiter(ctrl *gomock.Controller) *MockrateLimiter {
	mock := &MockrateLimiter{ctrl: ctrl}
	mock.recorder = &MockrateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrateLimiter) EXPECT() *MockrateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockrateLimiter) Allow(ctx context.Context, key string) (bool, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Allow indicates an expected call of Allow.
func (mr *MockrateLimiterMockRecorder) Allow(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockrateLimiter)(nil).Allow), ctx, key)
}
