// Code generated by MockGen. DO NOT EDIT.
// Source: generate.go
//
// Generated by this command:
//
//	mockgen -source=generate.go -destination=../../../test/mocks/httpapi/streamer_mock.go -package=mockhttpapi
//

// Package mockhttpapi is a generated GoMock package.
package mockhttpapi

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodvieira/pricing-optimizer-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockstreamer is a mock of streamer interface.
type Mockstreamer struct {
	ctrl     *gomock.Controller
	recorder *MockstreamerMockRecorder
	isgomock struct{}
}

// MockstreamerMockRecorder is the mock recorder for Mockstreamer.
type MockstreamerMockRecorder struct {
	mock *Mockstreamer
}

// NewMockstreamer creates a new mock instance.
func NewMockstreamer(ctrl *gomock.Controller) *Mockstreamer {
	mock := &Mockstreamer{ctrl: ctrl}
	mock.recorder = &MockstreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstreamer) EXPECT() *MockstreamerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *Mockstreamer) Execute(ctx context.Context, in domain.GenerateVariationsInput) (<-chan domain.GenerationEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(<-chan domain.GenerationEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockstreamerMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*Mockstreamer)(nil).Execute), ctx, in)
}
