// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AudiencePricePosition.
const (
	Budget    AudiencePricePosition = "budget"
	MidMarket AudiencePricePosition = "mid_market"
	Premium   AudiencePricePosition = "premium"
)

// Valid indicates whether the value is a known member of the AudiencePricePosition enum.
func (e AudiencePricePosition) Valid() bool {
	switch e {
	case Budget:
		return true
	case MidMarket:
		return true
	case Premium:
		return true
	default:
		return false
	}
}

// Defines values for AudienceSophistication.
const (
	High   AudienceSophistication = "high"
	Low    AudienceSophistication = "low"
	Medium AudienceSophistication = "medium"
)

// Valid indicates whether the value is a known member of the AudienceSophistication enum.
func (e AudienceSophistication) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ExportRequestFormat.
const (
	ExportRequestFormatHtml   ExportRequestFormat = "html"
	ExportRequestFormatJsx    ExportRequestFormat = "jsx"
	ExportRequestFormatStripe ExportRequestFormat = "stripe"
)

// Valid indicates whether the value is a known member of the ExportRequestFormat enum.
func (e ExportRequestFormat) Valid() bool {
	switch e {
	case ExportRequestFormatHtml:
		return true
	case ExportRequestFormatJsx:
		return true
	case ExportRequestFormatStripe:
		return true
	default:
		return false
	}
}

// Defines values for ExportResultFormat.
const (
	ExportResultFormatHtml   ExportResultFormat = "html"
	ExportResultFormatJsx    ExportResultFormat = "jsx"
	ExportResultFormatStripe ExportResultFormat = "stripe"
)

// Valid indicates whether the value is a known member of the ExportResultFormat enum.
func (e ExportResultFormat) Valid() bool {
	switch e {
	case ExportResultFormatHtml:
		return true
	case ExportResultFormatJsx:
		return true
	case ExportResultFormatStripe:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStatus.
const (
	Completed GenerationStatus = "completed"
	Failed    GenerationStatus = "failed"
	Pending   GenerationStatus = "pending"
	Streaming GenerationStatus = "streaming"
)

// Valid indicates whether the value is a known member of the GenerationStatus enum.
func (e GenerationStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Streaming:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusChecks.
const (
	HealthStatusChecksFail    HealthStatusChecks = "fail"
	HealthStatusChecksOk      HealthStatusChecks = "ok"
	HealthStatusChecksSkipped HealthStatusChecks = "skipped"
)

// Valid indicates whether the value is a known member of the HealthStatusChecks enum.
func (e HealthStatusChecks) Valid() bool {
	switch e {
	case HealthStatusChecksFail:
		return true
	case HealthStatusChecksOk:
		return true
	case HealthStatusChecksSkipped:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded HealthStatusStatus = "degraded"
	HealthStatusStatusOk       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDegraded:
		return true
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PriceInterval.
const (
	Monthly PriceInterval = "monthly"
	OneTime PriceInterval = "one_time"
	Yearly  PriceInterval = "yearly"
)

// Valid indicates whether the value is a known member of the PriceInterval enum.
func (e PriceInterval) Valid() bool {
	switch e {
	case Monthly:
		return true
	case OneTime:
		return true
	case Yearly:
		return true
	default:
		return false
	}
}

// Defines values for PricingStrategy.
const (
	Anchor     PricingStrategy = "anchor"
	Freemium   PricingStrategy = "freemium"
	ValueBased PricingStrategy = "value_based"
)

// Valid indicates whether the value is a known member of the PricingStrategy enum.
func (e PricingStrategy) Valid() bool {
	switch e {
	case Anchor:
		return true
	case Freemium:
		return true
	case ValueBased:
		return true
	default:
		return false
	}
}

// Defines values for SiteProfileSourceType.
const (
	Spa    SiteProfileSourceType = "spa"
	Static SiteProfileSourceType = "static"
)

// Valid indicates whether the value is a known member of the SiteProfileSourceType enum.
func (e SiteProfileSourceType) Valid() bool {
	switch e {
	case Spa:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for StreamChunkType.
const (
	Done               StreamChunkType = "done"
	Error              StreamChunkType = "error"
	GenerationStarted  StreamChunkType = "generation_started"
	Token              StreamChunkType = "token"
	VariationCompleted StreamChunkType = "variation_completed"
	VariationStarted   StreamChunkType = "variation_started"
)

// Valid indicates whether the value is a known member of the StreamChunkType enum.
func (e StreamChunkType) Valid() bool {
	switch e {
	case Done:
		return true
	case Error:
		return true
	case GenerationStarted:
		return true
	case Token:
		return true
	case VariationCompleted:
		return true
	case VariationStarted:
		return true
	default:
		return false
	}
}

// AnalyzeRequest defines model for AnalyzeRequest.
type AnalyzeRequest struct {
	// Url The product URL to analyze.
	Url string `json:"url"`
}

// Audience defines model for Audience.
type Audience struct {
	PricePosition *AudiencePricePosition `json:"pricePosition,omitempty"`

	// Segment e.g. "SaaS founders", "enterprise IT", "indie developers".
	Segment string `json:"segment"`

	// Sophistication Price/technical sophistication of the audience.
	Sophistication AudienceSophistication `json:"sophistication"`
}

// AudiencePricePosition defines model for Audience.PricePosition.
type AudiencePricePosition string

// AudienceSophistication Price/technical sophistication of the audience.
type AudienceSophistication string

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	Format      ExportRequestFormat `json:"format"`
	VariationId openapi_types.UUID  `json:"variationId"`
}

// ExportRequestFormat defines model for ExportRequest.Format.
type ExportRequestFormat string

// ExportResult defines model for ExportResult.
type ExportResult struct {
	// Content The exported artifact as text (JSX, HTML, or Stripe config JSON).
	Content string `json:"content"`

	// ContentType MIME type of the content, e.g. "text/plain".
	ContentType string `json:"contentType"`

	// Filename Suggested filename, e.g. "PricingSection.tsx".
	Filename string             `json:"filename"`
	Format   ExportResultFormat `json:"format"`
}

// ExportResultFormat defines model for ExportResult.Format.
type ExportResultFormat string

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Currency ISO 4217 currency code for generated prices.
	Currency    *string     `json:"currency,omitempty"`
	SiteProfile SiteProfile `json:"siteProfile"`

	// Strategies Strategies to generate. Defaults to all three when omitted. Duplicates are
	// rejected.
	Strategies *[]PricingStrategy `json:"strategies,omitempty"`
}

// Generation defines model for Generation.
type Generation struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	SiteProfile *SiteProfile       `json:"siteProfile,omitempty"`
	SourceUrl   string             `json:"sourceUrl"`
	Status      GenerationStatus   `json:"status"`
	Variations  []Variation        `json:"variations"`
}

// GenerationStatus defines model for Generation.Status.
type GenerationStatus string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Checks Per-dependency health, keyed by dependency name.
	Checks *map[string]HealthStatusChecks `json:"checks,omitempty"`
	Status HealthStatusStatus             `json:"status"`

	// Version Build version or git SHA.
	Version string `json:"version"`
}

// HealthStatusChecks defines model for HealthStatus.Checks.
type HealthStatusChecks string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Price defines model for Price.
type Price struct {
	// Amount Amount in the currency's minor unit (e.g. cents). 0 means free.
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`

	// CustomLabel Overrides the rendered price, e.g. "Contact us".
	CustomLabel *string       `json:"customLabel,omitempty"`
	Interval    PriceInterval `json:"interval"`
}

// PriceInterval defines model for Price.Interval.
type PriceInterval string

// PricingStrategy The psychological pricing strategy applied to a variation.
type PricingStrategy string

// PricingTier defines model for PricingTier.
type PricingTier struct {
	// Badge Optional badge text, e.g. "Most popular".
	Badge *string `json:"badge,omitempty"`

	// Cta Call-to-action label, e.g. "Start free".
	Cta      *string  `json:"cta,omitempty"`
	Features []string `json:"features"`

	// Highlighted Whether this tier is visually emphasized as the recommended plan.
	Highlighted *bool `json:"highlighted,omitempty"`

	// Name e.g. "Free", "Pro", "Enterprise".
	Name    string  `json:"name"`
	Price   Price   `json:"price"`
	Tagline *string `json:"tagline,omitempty"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`

	// TraceId Correlation id for logs and traces.
	TraceId              *string                `json:"traceId,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SiteProfile defines model for SiteProfile.
type SiteProfile struct {
	AnalyzedAt time.Time `json:"analyzedAt"`
	Audience   Audience  `json:"audience"`

	// Industry Classified industry, e.g. "developer-tools", "e-commerce".
	Industry string `json:"industry"`

	// Keywords Salient terms extracted from the page.
	Keywords *[]string `json:"keywords,omitempty"`

	// SourceType Which scraper handled the page.
	SourceType SiteProfileSourceType `json:"sourceType"`
	Title      string                `json:"title"`
	Url        string                `json:"url"`

	// ValueProposition One-to-two sentence summary of what the product offers.
	ValueProposition string `json:"valueProposition"`
}

// SiteProfileSourceType Which scraper handled the page.
type SiteProfileSourceType string

// StreamChunk One event in the generation SSE stream. `type` discriminates the payload:
// - `generation_started`: carries `generationId`.
// - `variation_started`: a variation began; carries `strategy`.
// - `token`: an incremental text delta for a variation; carries `strategy`, `delta`.
// - `variation_completed`: a finished variation; carries `variation`.
// - `done`: terminal success; carries the full `generation`.
// - `error`: terminal failure; carries `problem`.
type StreamChunk struct {
	Delta        *string             `json:"delta,omitempty"`
	Generation   *Generation         `json:"generation,omitempty"`
	GenerationId *openapi_types.UUID `json:"generationId,omitempty"`

	// Problem RFC 7807 problem details.
	Problem *Problem `json:"problem,omitempty"`

	// Strategy The psychological pricing strategy applied to a variation.
	Strategy  *PricingStrategy `json:"strategy,omitempty"`
	Type      StreamChunkType  `json:"type"`
	Variation *Variation       `json:"variation,omitempty"`
}

// StreamChunkType defines model for StreamChunk.Type.
type StreamChunkType string

// Variation defines model for Variation.
type Variation struct {
	Headline string             `json:"headline"`
	Id       openapi_types.UUID `json:"id"`

	// Rationale Why this strategy fits the analyzed audience.
	Rationale *string `json:"rationale,omitempty"`

	// Strategy The psychological pricing strategy applied to a variation.
	Strategy    PricingStrategy `json:"strategy"`
	Subheadline *string         `json:"subheadline,omitempty"`
	Tiers       []PricingTier   `json:"tiers"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// InternalError RFC 7807 problem details.
type InternalError = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// TooManyRequests RFC 7807 problem details.
type TooManyRequests = Problem

// UnprocessableEntity RFC 7807 problem details.
type UnprocessableEntity = Problem

// GenerateVariationsParams defines parameters for GenerateVariations.
type GenerateVariationsParams struct {
	// IdempotencyKey Client-supplied key to make generation idempotent. Repeating a request with the
	// same key once the first has completed returns the same generation instead of
	// producing a new one. A repeat request with the same key while the first is still
	// in progress gets 409 Conflict instead of starting a second, redundant generation.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// AnalyzeSiteJSONRequestBody defines body for AnalyzeSite for application/json ContentType.
type AnalyzeSiteJSONRequestBody = AnalyzeRequest

// ExportVariationJSONRequestBody defines body for ExportVariation for application/json ContentType.
type ExportVariationJSONRequestBody = ExportRequest

// GenerateVariationsJSONRequestBody defines body for GenerateVariations for application/json ContentType.
type GenerateVariationsJSONRequestBody = GenerateRequest

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["traceId"]; found {
		err = json.Unmarshal(raw, &a.TraceId)
		if err != nil {
			return fmt.Errorf("error reading 'traceId': %w", err)
		}
		delete(object, "traceId")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	if a.TraceId != nil {
		object["traceId"], err = json.Marshal(a.TraceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traceId': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Analyze a product URL and return a site profile.
	// (POST /v1/analyze)
	AnalyzeSite(w http.ResponseWriter, r *http.Request)
	// Export one variation of a generation in the requested format.
	// (POST /v1/export/{id})
	ExportVariation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Generate three pricing-page variations (SSE stream).
	// (POST /v1/generate)
	GenerateVariations(w http.ResponseWriter, r *http.Request, params GenerateVariationsParams)
	// Fetch a previously produced generation.
	// (GET /v1/generations/{id})
	GetGeneration(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Liveness and readiness probe.
	// (GET /v1/healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Analyze a product URL and return a site profile.
// (POST /v1/analyze)
func (_ Unimplemented) AnalyzeSite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export one variation of a generation in the requested format.
// (POST /v1/export/{id})
func (_ Unimplemented) ExportVariation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate three pricing-page variations (SSE stream).
// (POST /v1/generate)
func (_ Unimplemented) GenerateVariations(w http.ResponseWriter, r *http.Request, params GenerateVariationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a previously produced generation.
// (GET /v1/generations/{id})
func (_ Unimplemented) GetGeneration(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness and readiness probe.
// (GET /v1/healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AnalyzeSite operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeSite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeSite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportVariation operation middleware
func (siw *ServerInterfaceWrapper) ExportVariation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportVariation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVariations operation middleware
func (siw *ServerInterfaceWrapper) GenerateVariations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GenerateVariationsParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVariations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGeneration operation middleware
func (siw *ServerInterfaceWrapper) GetGeneration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/analyze", wrapper.AnalyzeSite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/export/{id}", wrapper.ExportVariation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/generate", wrapper.GenerateVariations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/generations/{id}", wrapper.GetGeneration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/healthz", wrapper.HealthCheck)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fptc9u2k/8qO7z/zCVzlOykzbRVX7mpm7qXNJ7IfZircjVMrEjUIMACoG01o+9+swBIgRLlp7skc+8k",
	"kgAWu4vf/naxH7JC141WqJzNZh+yhhlWo0Pj/51wrBvtUBWr/8QVPeFoCyMaJ7TKZtlLKVC5iW2bRgrk",
	"cIkrcBpqdolQokLD6EMQ3TRuCu+wQeaEKoGBwb9btA6uhavAVbhQltXoZ9GqQHoES2Gsg4pZIEElOuRg",
	"0LVGWf/ej0jXUtYh46CXC9UYzdsirKXwGrTCKRyB8SLsrA794teVkOnqwoJ1QsqFEgoao0uD1kKJzsKX",
	"h9/AS62WUhQuWRusYybu0mKhFc/BIG8VZ8ol4k4XKsszQbqskHE0WZ4pVmM2S3U/IeXnmS0qrBlZoWY3",
	"r1GVrspmz1+8yLNaqO7/13nmVg1NYJ0RqszW63WeGbSNVha9Vb9j/F3YO/0rtCLL0E9GZiy8YAeN0RcS",
	"6//4y5KlPySL/8vgMptl/3aw8ZyD8NYenIZRYdGhr5xVuFE5s1AzudSmRj7N1nnW6fBTSnSU+s3QC7aU",
	"Tx7ApEHGV5C4wBR+Y8LBUhsQDpxeqKVQwlY5TaTITc1qxL2cJt8B4SwYtK10OWgDrcXopvEb70ILxRS0",
	"yqBk5PlDz1nn2YlyaBSTx8Zo80mVR2LhTYMFyYW0POiiaI2JFv1Zux90q/hn8jEPE1a3pkDgGi0o7QBv",
	"hHVeujOt3zC1iufAfkoh3zGHIEUtSJ4CkZPC8nj+vSTvyHEmR0uHZhdz5x5OLHnINXnfBS61weBsQpXT",
	"IVAIJeq2zmaHPSwI5bBEQ5Kt8+wXAskCrWUXEo+VE271OUHhGqWcBFiAi9aBxZopJwomJZ28KyYFede6",
	"26NX15FicvUPJpjGOBe0ApOnRjdonCDkWzJpMc+a5NGHrDVyV8ckVggeDn5595p0zcIipF68YRSJbDb7",
	"I6uca+zs4CA+mxa6zt7nGW2BuWyWtUZku4hMgPx3KwxymoNEeN9/pC/+wsKRjx61XKAq8IE7aowo8FRb",
	"ETbzIUNFHvBHdtHyEl1G4YL/WTNz6f80BmvR1okEnZh5ZrGsoxsMFYTTcgqLbM7YHJZ0ytHYRZbDIkMC",
	"pMYIi3ByFh4JxQUCxyuUJKddZNNsbDHdVMK66Gu7a57Svg4cFpUih4Dh9xR0CWVZVJo3VNy41Ne0a+S0",
	"zzyrRFmNbHfLKt3edwQbM9XxTaONe5wHdr6yMdRf9obEdLWk1Z0RDY6a54oZ4WU64elEWdsKfqfXpYN7",
	"h71tbxSpHri1BEZ2Dxj6eZEDMaUlKxwwCw5vHDz5af57Dj+evXntI+PcawAKrZaihJ/mb39+OupAcbUz",
	"/3x7xTcnb46BhnSOEr/OIfoyrXzQSCbUHv9cComBm+1AcluWIeR03/SzktMKVc6x8EHb2Zt9sz/SC7as",
	"GqdJpB3qpf83aupXgV48Ekp98FdFzBOWzPtL9sv8+2wb9k/mb+HL58++gm4IFJqjJ1KR4SAHj2OWlNUw",
	"Rywnm2X//cfR5L/ef/hi/a9RBBEOT42mrd8Vk+bJp2uvXuawjBvZsm7/LjC3IN8Uvg9b9E+ZlOAqgwjX",
	"xPx0LZxDPoXv2xA80QIzuFAG//KEKfJ+h7W9O3oGDwpSrEjamt2chKFfeO4f/zzrVcKMYatdREv2fIv1",
	"I/g+xPAGyWJHboBCnDmcOOFdcMdU4j6I9b+yqKd+v4Tofns4JvMz19r08DWoOL30roGsDr/7FJQOGBMS",
	"+e247Ke8l5V/7YbQ+Fut6BW12V0v/GDZPLHJmKl/RCZdNe+3/RBjV1hc3jJoo0N9GdVEQl6Kptmjrq0w",
	"j2bCkfTvgaHykuaUFBEnXEHyjvAtAdPN9nbt6WXhWBrG9xkNjR3lHd+1QnKIrykelcLB/Mej6Z0hdmOZ",
	"OPeYKTyteaANWK3bsbB65J9TiuojXATXf7dQC0UpphIOnvjIVJD3PZ3CIdTIlIWlQa/K2xKGfIDw9wXl",
	"orVO16/ZBY4Q7bdXaIzgGGo5hgxrOujvY+hLrRzRg3YfcyQJzRWTA4Mr/DOCT62Vq+Qqy7MVMiNXd0fR",
	"qN9kw8ki+4yYgvR4RmFXRaWlLj19bcIQiKFnBSwW0SicQH+WUx7LVFFpQ4fKYCDtdOhli39eMLvHraNk",
	"ZyLkkg9wsgvGyxGy87YJ48G/94Stt9QbbR00umklM3tsVTg2UkdkUk6cnjDPkkCSs/STzh0zzjvoPuqE",
	"zLUGh2C789UQVEMWIEVZEZqnhCXqYijgbxW6Cg24SlhwAg0IC1fCtj4xxbqpmBX/EJftPLnQdU3uzKGR",
	"TCVyX2gtkXmcH2eTcds/+A3nnkPq8OO4z632aKLpsOQuQuFDpGOlFApHtLV1HCKPDLMn+h4/CSHZ3+tr",
	"zrQ76n33w0v46uvDryAWGICjY0IG8jdwyvBi1MBCWcdiunxLhK/ZTUC4F998k+Dds8NRxHPCyfEZnWEF",
	"nvARZ9bGl+tC5duTWqlLC0xx8IPsqO1cn7Z0zJld6NbNLiRTl9kDSwpB7H7bY4aaD6nVQ6JPKIU8iO+x",
	"pJZxm3P2NQ9vUN5aZ0bvHZi1Yklo2X3Uw0VfZ5g4rWVXlZj482iKfSfnElfX2vAx+s/8JQc4NLUFvCET",
	"+lTP6Nqf9YaVPnTeH3oCexvPU3+rRFGBLQxr0EDFFJcUE5J1umhgGxYtLIpR6N/vu+39aLGPLeQOSTFp",
	"KxgoJNx21xosUl5ZINi2rplZUZ59XTEXZI/FNL1corHTe5XE8t6Ld+RIfCNxrYFi89RNR/3f8/qXVasu",
	"7/T/nU0DXuGGaCXXCPP5MYSMYQrntOY5cEGDa6F8GhgsuZKa8dlCTeB8M/hPX/FHfj6DghlDCWfy9oSf",
	"T/2Anhok3yeEAS6wZOrbzRQdwYjDnb5ERUMUCFUYrFE5JkPhhaN0zCNWMuHYVDmc+293ROozJC9UuA5B",
	"PjpZ/yxOwrXC85k/Z4L4hW2LAq3djPAXcq2UqVbiWH//kA6mtKM1mCwXQ8t5SL23o4oMtGTnCJSDnPg2",
	"5Eqy58G4k/tlus0mbt6rlt7XLFaPKCB0saaDkl0fTNPJ5Jl3nsG7NCUmCxJA+buoWxPjB6TD25Ft1YxX",
	"L35N535ANKuQ8T006N5liqA7JkfxfBVYY8/zl8IFX+4AalCzHmEujzazbS9u3R0R2fuXKNJMYlCEevGQ",
	"IlQoX3RC5hv1d+Ls2nbtucBSdxVlFq6J4z35O82NKDX8KlAYiog+uPUXM6VwVXsxLXR9YDS/Ch/tFh1i",
	"MkbJTS3+QdMZxwIb3AQRietKgDaW/GImN6EAvVCbKkwOyIrK53Wr0ArAhXVCFe6OVHChnoRUr3uTQ5fx",
	"gWSco8nBx8SJz/ueTqF3fl9njBIj95fPC2WdaQui7Bxev34DxIugYFJ6oRSPASuknr5wEBiPvkIDczRX",
	"aCZzenBMQc9OF2qhzsiluS7a2sfB2IshVCkR4q2rXoIzrat8PKHXP56dnfqyOzGoKVBK/ErDBSsuUfGF",
	"2qg1sB4TKfOqQRvYlnBwJRho1ohJoTmWqL4NUcH4onZqGuHsQsWN+EENKhrnp/OWn8LPGoxuHYKtRGO9",
	"snTrgIFtsIC2IUYbWkBC0JCiQGUxcb43J2fhoHnKk836CjocnUwafd1XM0jV5B9xJwOnmvZUZ8wRj05P",
	"kgrSLDucPpse0qJxR9ks+8I/8nXyyh/jg6tnB9GBfalG25Fi0Q/oiiqGVXLtJ0VldI288Qabnx7ZHApN",
	"+S39Dzwz7OFp3vHgMNr7om+36Rha7k1XdDTd9jTdP+/xDsL9r22l75VJUhIQdqFobqGa1iWF975phjC8",
	"D7DdHTDNkAXAQeu+0/y22+yH3WJv3TKvh8BGWe12n83zw8P/s9UH1e3de3R6vYknkTkRV1r5bocvgyRj",
	"C/QSHyRtQTTk+fO7h4x1D/ix39w9drsDY51nL+4j5rDjxY96/qlbFhwzJTqwpPVCt5L77pILhKU/UxwI",
	"upmx2DUr9PgQvWgkqoSmNgIfmrUJtvbQwEobqn9Mrqyw2Xuako54uEE9+CD4ev8xf+eLqtZP7OF5kykw",
	"evrT/HfoNZDTOVecSa1wcwHL4hXsQnXwdEYG91ex8Vq2jUeTMDXe1x6dnvgoE0JSzTh+C1rJVXeRSye8",
	"C1RjRzrcO29oXT5oTvxjrMI66Dmcdp11BIubvjpPQIYHN+2YuesS/f3HQZdhA8EnBpfBDf8el9+5rX80",
	"sBx+efeQvnnskagwOHNhe0AuvfF9vQQ27BuNhduueyw4QnoAgwo2x68jG/vP3qstprjhhr6NkBkmpa90",
	"E0/0jYIJR+zYYJ5wtHBkQv8ps2PkzIfU8DFgTalGUugIZQsLrXJCAluoPl8O2Tc80aZLpp+Gj8OEm97b",
	"V4nKLDBptW89E3hFkLBQbOnQXDPDraddr47PINEVbd3j1diB77T1a3qPuXXmx7xg88nBVsPyxzqt230S",
	"jzqvvuHE63gS7PUANpDUrsZ7M0N9KvqBXg6cIORVdgrH5Hbz+TGcc+bY7BwoEfMMnQll6cAsFGH8BBXR",
	"bZ7OMnQ0xW3nv0VYYxmabYJfBWsnHY6/TzZ+NBkrotPkggPxx1J1mYmwyYnNg/NhaLXozm+svWUPgfT1",
	"Y4HsHiyn72v+f0SpxhOa3Vw3hbMnm8Ln0xQzk/rZNm72WEAClujPxDYguKSqtoMFHym4f6Qgm9YHx0Ns",
	"Eo0I8Qm7Nxqefp7Y6ZNEz1bxSujWytWmuJBkZHdYPDRx/LPX0KEd5WWFxWX2EU0w6HoZy6LQXImCcs/Y",
	"dhKypxeHX3wOEbpulcDAk7YXQQGcXTEhCSO2M4zX4gqV5wc+qWBc+H+UBw3SCd34TMJ3+RKLGOPUr3XB",
	"ZNe5G7thN+W12cGBpA8qbd3s68OvD328jfPvXKP5G620LLBKkiDKeaabY9ynOut8H6XqciZiHnthKZmy",
	"TMvz25NGhkjBS1tUw+6LOEFkf7uD33auzCQFwkYL4mGbgaTo9fv1/wQAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
