// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AudiencePricePosition.
const (
	Budget    AudiencePricePosition = "budget"
	MidMarket AudiencePricePosition = "mid_market"
	Premium   AudiencePricePosition = "premium"
)

// Valid indicates whether the value is a known member of the AudiencePricePosition enum.
func (e AudiencePricePosition) Valid() bool {
	switch e {
	case Budget:
		return true
	case MidMarket:
		return true
	case Premium:
		return true
	default:
		return false
	}
}

// Defines values for AudienceSophistication.
const (
	High   AudienceSophistication = "high"
	Low    AudienceSophistication = "low"
	Medium AudienceSophistication = "medium"
)

// Valid indicates whether the value is a known member of the AudienceSophistication enum.
func (e AudienceSophistication) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ExportRequestFormat.
const (
	ExportRequestFormatHtml   ExportRequestFormat = "html"
	ExportRequestFormatJsx    ExportRequestFormat = "jsx"
	ExportRequestFormatStripe ExportRequestFormat = "stripe"
)

// Valid indicates whether the value is a known member of the ExportRequestFormat enum.
func (e ExportRequestFormat) Valid() bool {
	switch e {
	case ExportRequestFormatHtml:
		return true
	case ExportRequestFormatJsx:
		return true
	case ExportRequestFormatStripe:
		return true
	default:
		return false
	}
}

// Defines values for ExportResultFormat.
const (
	ExportResultFormatHtml   ExportResultFormat = "html"
	ExportResultFormatJsx    ExportResultFormat = "jsx"
	ExportResultFormatStripe ExportResultFormat = "stripe"
)

// Valid indicates whether the value is a known member of the ExportResultFormat enum.
func (e ExportResultFormat) Valid() bool {
	switch e {
	case ExportResultFormatHtml:
		return true
	case ExportResultFormatJsx:
		return true
	case ExportResultFormatStripe:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStatus.
const (
	Completed GenerationStatus = "completed"
	Failed    GenerationStatus = "failed"
	Pending   GenerationStatus = "pending"
	Streaming GenerationStatus = "streaming"
)

// Valid indicates whether the value is a known member of the GenerationStatus enum.
func (e GenerationStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Streaming:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusChecks.
const (
	HealthStatusChecksFail    HealthStatusChecks = "fail"
	HealthStatusChecksOk      HealthStatusChecks = "ok"
	HealthStatusChecksSkipped HealthStatusChecks = "skipped"
)

// Valid indicates whether the value is a known member of the HealthStatusChecks enum.
func (e HealthStatusChecks) Valid() bool {
	switch e {
	case HealthStatusChecksFail:
		return true
	case HealthStatusChecksOk:
		return true
	case HealthStatusChecksSkipped:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded HealthStatusStatus = "degraded"
	HealthStatusStatusOk       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDegraded:
		return true
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PriceInterval.
const (
	Monthly PriceInterval = "monthly"
	OneTime PriceInterval = "one_time"
	Yearly  PriceInterval = "yearly"
)

// Valid indicates whether the value is a known member of the PriceInterval enum.
func (e PriceInterval) Valid() bool {
	switch e {
	case Monthly:
		return true
	case OneTime:
		return true
	case Yearly:
		return true
	default:
		return false
	}
}

// Defines values for PricingStrategy.
const (
	Anchor     PricingStrategy = "anchor"
	Freemium   PricingStrategy = "freemium"
	ValueBased PricingStrategy = "value_based"
)

// Valid indicates whether the value is a known member of the PricingStrategy enum.
func (e PricingStrategy) Valid() bool {
	switch e {
	case Anchor:
		return true
	case Freemium:
		return true
	case ValueBased:
		return true
	default:
		return false
	}
}

// Defines values for SiteProfileSourceType.
const (
	Spa    SiteProfileSourceType = "spa"
	Static SiteProfileSourceType = "static"
)

// Valid indicates whether the value is a known member of the SiteProfileSourceType enum.
func (e SiteProfileSourceType) Valid() bool {
	switch e {
	case Spa:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for StreamChunkType.
const (
	Done               StreamChunkType = "done"
	Error              StreamChunkType = "error"
	GenerationStarted  StreamChunkType = "generation_started"
	Token              StreamChunkType = "token"
	VariationCompleted StreamChunkType = "variation_completed"
	VariationStarted   StreamChunkType = "variation_started"
)

// Valid indicates whether the value is a known member of the StreamChunkType enum.
func (e StreamChunkType) Valid() bool {
	switch e {
	case Done:
		return true
	case Error:
		return true
	case GenerationStarted:
		return true
	case Token:
		return true
	case VariationCompleted:
		return true
	case VariationStarted:
		return true
	default:
		return false
	}
}

// AnalyzeRequest defines model for AnalyzeRequest.
type AnalyzeRequest struct {
	// Url The product URL to analyze.
	Url string `json:"url"`
}

// Audience defines model for Audience.
type Audience struct {
	PricePosition *AudiencePricePosition `json:"pricePosition,omitempty"`

	// Segment e.g. "SaaS founders", "enterprise IT", "indie developers".
	Segment string `json:"segment"`

	// Sophistication Price/technical sophistication of the audience.
	Sophistication AudienceSophistication `json:"sophistication"`
}

// AudiencePricePosition defines model for Audience.PricePosition.
type AudiencePricePosition string

// AudienceSophistication Price/technical sophistication of the audience.
type AudienceSophistication string

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	Format      ExportRequestFormat `json:"format"`
	VariationId openapi_types.UUID  `json:"variationId"`
}

// ExportRequestFormat defines model for ExportRequest.Format.
type ExportRequestFormat string

// ExportResult defines model for ExportResult.
type ExportResult struct {
	// Content The exported artifact as text (JSX, HTML, or Stripe config JSON).
	Content string `json:"content"`

	// ContentType MIME type of the content, e.g. "text/plain".
	ContentType string `json:"contentType"`

	// Filename Suggested filename, e.g. "PricingSection.tsx".
	Filename string             `json:"filename"`
	Format   ExportResultFormat `json:"format"`
}

// ExportResultFormat defines model for ExportResult.Format.
type ExportResultFormat string

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Currency ISO 4217 currency code for generated prices.
	Currency    *string     `json:"currency,omitempty"`
	SiteProfile SiteProfile `json:"siteProfile"`

	// Strategies Strategies to generate. Defaults to all three when omitted. Duplicates are
	// rejected.
	Strategies *[]PricingStrategy `json:"strategies,omitempty"`
}

// Generation defines model for Generation.
type Generation struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	SiteProfile *SiteProfile       `json:"siteProfile,omitempty"`
	SourceUrl   string             `json:"sourceUrl"`
	Status      GenerationStatus   `json:"status"`
	Variations  []Variation        `json:"variations"`
}

// GenerationStatus defines model for Generation.Status.
type GenerationStatus string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Checks Per-dependency health, keyed by dependency name.
	Checks *map[string]HealthStatusChecks `json:"checks,omitempty"`
	Status HealthStatusStatus             `json:"status"`

	// Version Build version or git SHA.
	Version string `json:"version"`
}

// HealthStatusChecks defines model for HealthStatus.Checks.
type HealthStatusChecks string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Price defines model for Price.
type Price struct {
	// Amount Amount in the currency's minor unit (e.g. cents). 0 means free.
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`

	// CustomLabel Overrides the rendered price, e.g. "Contact us".
	CustomLabel *string       `json:"customLabel,omitempty"`
	Interval    PriceInterval `json:"interval"`
}

// PriceInterval defines model for Price.Interval.
type PriceInterval string

// PricingStrategy The psychological pricing strategy applied to a variation.
type PricingStrategy string

// PricingTier defines model for PricingTier.
type PricingTier struct {
	// Badge Optional badge text, e.g. "Most popular".
	Badge *string `json:"badge,omitempty"`

	// Cta Call-to-action label, e.g. "Start free".
	Cta      *string  `json:"cta,omitempty"`
	Features []string `json:"features"`

	// Highlighted Whether this tier is visually emphasized as the recommended plan.
	Highlighted *bool `json:"highlighted,omitempty"`

	// Name e.g. "Free", "Pro", "Enterprise".
	Name    string  `json:"name"`
	Price   Price   `json:"price"`
	Tagline *string `json:"tagline,omitempty"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`

	// TraceId Correlation id for logs and traces.
	TraceId              *string                `json:"traceId,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SiteProfile defines model for SiteProfile.
type SiteProfile struct {
	AnalyzedAt time.Time `json:"analyzedAt"`
	Audience   Audience  `json:"audience"`

	// Industry Classified industry, e.g. "developer-tools", "e-commerce".
	Industry string `json:"industry"`

	// Keywords Salient terms extracted from the page.
	Keywords *[]string `json:"keywords,omitempty"`

	// SourceType Which scraper handled the page.
	SourceType SiteProfileSourceType `json:"sourceType"`
	Title      string                `json:"title"`
	Url        string                `json:"url"`

	// ValueProposition One-to-two sentence summary of what the product offers.
	ValueProposition string `json:"valueProposition"`
}

// SiteProfileSourceType Which scraper handled the page.
type SiteProfileSourceType string

// StreamChunk One event in the generation SSE stream. `type` discriminates the payload:
// - `generation_started`: carries `generationId`.
// - `variation_started`: a variation began; carries `strategy`.
// - `token`: an incremental text delta for a variation; carries `strategy`, `delta`.
// - `variation_completed`: a finished variation; carries `variation`.
// - `done`: terminal success; carries the full `generation`.
// - `error`: terminal failure; carries `problem`.
type StreamChunk struct {
	Delta        *string             `json:"delta,omitempty"`
	Generation   *Generation         `json:"generation,omitempty"`
	GenerationId *openapi_types.UUID `json:"generationId,omitempty"`

	// Problem RFC 7807 problem details.
	Problem *Problem `json:"problem,omitempty"`

	// Strategy The psychological pricing strategy applied to a variation.
	Strategy  *PricingStrategy `json:"strategy,omitempty"`
	Type      StreamChunkType  `json:"type"`
	Variation *Variation       `json:"variation,omitempty"`
}

// StreamChunkType defines model for StreamChunk.Type.
type StreamChunkType string

// Variation defines model for Variation.
type Variation struct {
	Headline string             `json:"headline"`
	Id       openapi_types.UUID `json:"id"`

	// Rationale Why this strategy fits the analyzed audience.
	Rationale *string `json:"rationale,omitempty"`

	// Strategy The psychological pricing strategy applied to a variation.
	Strategy    PricingStrategy `json:"strategy"`
	Subheadline *string         `json:"subheadline,omitempty"`
	Tiers       []PricingTier   `json:"tiers"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// InternalError RFC 7807 problem details.
type InternalError = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// TooManyRequests RFC 7807 problem details.
type TooManyRequests = Problem

// UnprocessableEntity RFC 7807 problem details.
type UnprocessableEntity = Problem

// GenerateVariationsParams defines parameters for GenerateVariations.
type GenerateVariationsParams struct {
	// IdempotencyKey Client-supplied key to make generation idempotent. Repeating a request with the
	// same key returns the same generation instead of producing a new one.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// AnalyzeSiteJSONRequestBody defines body for AnalyzeSite for application/json ContentType.
type AnalyzeSiteJSONRequestBody = AnalyzeRequest

// ExportVariationJSONRequestBody defines body for ExportVariation for application/json ContentType.
type ExportVariationJSONRequestBody = ExportRequest

// GenerateVariationsJSONRequestBody defines body for GenerateVariations for application/json ContentType.
type GenerateVariationsJSONRequestBody = GenerateRequest

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["traceId"]; found {
		err = json.Unmarshal(raw, &a.TraceId)
		if err != nil {
			return fmt.Errorf("error reading 'traceId': %w", err)
		}
		delete(object, "traceId")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	if a.TraceId != nil {
		object["traceId"], err = json.Marshal(a.TraceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traceId': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Analyze a product URL and return a site profile.
	// (POST /v1/analyze)
	AnalyzeSite(w http.ResponseWriter, r *http.Request)
	// Export one variation of a generation in the requested format.
	// (POST /v1/export/{id})
	ExportVariation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Generate three pricing-page variations (SSE stream).
	// (POST /v1/generate)
	GenerateVariations(w http.ResponseWriter, r *http.Request, params GenerateVariationsParams)
	// Fetch a previously produced generation.
	// (GET /v1/generations/{id})
	GetGeneration(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Liveness and readiness probe.
	// (GET /v1/healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Analyze a product URL and return a site profile.
// (POST /v1/analyze)
func (_ Unimplemented) AnalyzeSite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export one variation of a generation in the requested format.
// (POST /v1/export/{id})
func (_ Unimplemented) ExportVariation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate three pricing-page variations (SSE stream).
// (POST /v1/generate)
func (_ Unimplemented) GenerateVariations(w http.ResponseWriter, r *http.Request, params GenerateVariationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a previously produced generation.
// (GET /v1/generations/{id})
func (_ Unimplemented) GetGeneration(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness and readiness probe.
// (GET /v1/healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AnalyzeSite operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeSite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeSite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportVariation operation middleware
func (siw *ServerInterfaceWrapper) ExportVariation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportVariation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVariations operation middleware
func (siw *ServerInterfaceWrapper) GenerateVariations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GenerateVariationsParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVariations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGeneration operation middleware
func (siw *ServerInterfaceWrapper) GetGeneration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/analyze", wrapper.AnalyzeSite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/export/{id}", wrapper.ExportVariation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/generate", wrapper.GenerateVariations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/generations/{id}", wrapper.GetGeneration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/healthz", wrapper.HealthCheck)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fpvc9s2k/8qO7xn5pI5SnbSZtqqr9zUSd1LGk/k9ulclashYkWiBgE+AChbzfi73ywAUqBE+U/u0s7c",
	"O4kkgP2/v13sx6zQdaMVKmez2cesYYbV6ND4f2cc60Y7VMXmP3FDTzjawojGCa2yWfZSClRuYtumkQI5",
	"XOEGnIaaXSGUqNAw+hBEt42bwntskDmhSmBg8F8tWgfXwlXgKlwoy2r0uxh0rVGWnoJ/mG6nrEPGQa+g",
	"MZq3RdhN4TVohdOFyvJMEHkVMo4myzPFasxmKTsT4ifPbFFhzYixmt28QVW6Kps9f/Eiz2qhuv9f55nb",
	"NLSBdUaoMru9vc0zg7bRyqIX1HeMvw/M0L9CK2KWfjKSTOHpPmqMXkqs/+MPS8L7mBz+D4OrbJb929FW",
	"GUfhrT06D6vCoUPxX1S4lSGzUDO50qZGPs1u8+xMOTSKyVNjtPkryTpR0Cq8abBwyAHpeNBF0RoTKftJ",
	"u1e6VfxvkhVyMGh1awoErtGC0g7wRljnqbvQ+i1Tm6hP+1cS+Z45BClqQfQUiJwElkc79pS8R2c2k5OV",
	"Q7PvjnMstOKWXPCaCQdLXGlDbDuzEaqcDg1eKFG3dTY77s1bKIclGqLsNs9+Vo3RBVrLlhJPlRNu83ca",
	"9zVKOQnmDcvWgcWaKScKJuUGhFozKci6bjsevbhOFJObPzHxTca5oBOYPDe6QeMEefCKSYt51iSPPmat",
	"kfsyJrJC1HHw8/s3JGsWDiHx4g2rG0nLf8sq5xo7OzqKz6aFrrMPeUYsMJfNstaIbD+yUGD5VysMctqD",
	"SPjQf6SXf2DhyEZPWi5QFfhIjhojCjzXVgRmPmaoyAJ+y5YtL9FlFPb47zUzV/5PY7AWbZ1Q0JGZZxbL",
	"OprBUEA4LaewyOaMzWFFXo7GLrIcFhlSQGqMsAhnF+GRUFwgcFyjJDrtIptmY4fpphLWRVvbP/Oc+Dpy",
	"WFSKDAKG31OioDzCotC8oiLjUl8T18iJzzyrRFmNsLujlY73PcLGVHV602jjPs0CO1vZKuoPe0NkulrS",
	"6c6IBkfVs2ZGeJrOeLpR1raC32t16eLeYO/izbbysawlYWTfwdDvixyYcWLFCgfMgsMbB09+nP+aww8X",
	"b9/koA3MvQSg0GolSvhx/u6np6MGFE+78M93T3x79vYUaElnKPHrHKIt08lHjWRCHbDPlZAYMMZeSG7L",
	"MqSc7pt+VzJaoco5FvTt1NmbQ7t/ohXsaDVuk1A7lEv/b1TVrwP++sRQ6pO/KiKEXDFvL9nP8++z3bB/",
	"Nn8HXz5/9hV0S6DQHGGlTQcBkYOPY5aE1TBHKCebZf/928nkvz58/OL2H6MRRDg8N5pYvy8nzZNPb714",
	"mcMyMrKj3f4d5YGOvil8H1j0T5mU4CqDCNcVKtC1cA75FL5vQ/JEC8zgQhn8wwOmiF8d1vb+7BksKFCx",
	"IWprdnMWln7hMWz886wXCTOGbfYjWsLzHdqPwfcxijdIGjtxgyjEmcOJE94E91QlHhKx/lca9dDv55Dd",
	"707HpH7mWps6X4OK00tvGsjq8JuOlejQR0wmJPK747Lf8kFa/qVbQuvv1KIX1Ja7nvjBsXmikzFV/4BM",
	"umres/0YZVdYXN2xaCtDfRXFREReiaY5IK6dNI9mwpHk7wND5SnNqV4kTLiB5B3FtySYbtnb16enhWNp",
	"GD+kNDR2FHd81wrJIb6mfFQKB/MfTqb3ptitZuLeY6rwsOaROmC1bsfS6ol/DkKFDBeD679bqIXSBlol",
	"HDzxmakg63s6hWOokSkLK4NelHcVDPkgwj80KBetdbp+w5Y4ArTfrdEYwTH0AAwp1nShv8+hL7VyBA/a",
	"Q8iRKDRrJgcKV/h7DD61Vq6SmyzPNsiM3NyfRaN8E4aTQw4pMQ3S4xWF3RSVlrr08LUJSyCmng2w2F+h",
	"dAK9L6c4lqmi0oacymAA7eT0ssXfl8weMOtI2YUIteQjjGzJeDkCdt41YT349x6w9Zp6q62DRjetZOaA",
	"rgrHRlpMTMqJ0xPmURJIMpZ+07ljxnkDPQSdkLnW4DDY7n01DKqhCpCirCiap4AlymJI4D8rdBUacJWw",
	"4AQaEBbWwra+MMW6qZgVfxKW7Sy50HVN5syhkUwldC+1lsh8nB9Hk5HtV57h3GNIHX6c9rXVAUk0XSy5",
	"D1D4FOlYKYXCEWntuEPEkWH3RN7jnhCK/YO25ky7J973r17CV18ffwWxwQAcHRMygL+BUYYXowoWyjoW",
	"y+U7MnzNbkKEe/HNN0m8e3Y8GvGccHJ8R2dYgWd8xJi1MSi7pqgHtVKXFpji4BfZUd25vmzpkDNb6tbN",
	"lpKpq+yRLYVAds/2mKLmQ2j1mOwTWiGPwnss6WXcZZx9z8MrlLfWmdGWNLNWrChadh/14aLvM0yc1rLr",
	"Sky8P5rikOdc4eZaGz4G/5nvf4NDU1vAG1KhL/WMrr2vN6z0qfPhoSegt/E69Z+VKCqwhWENGqiY4pJy",
	"QnJOlw1sw6KGRTEa+g/bbvswWOxzC5lD0kzaSQYKKW67aw0Wqa4sEGxb18xsqM6+rpgLtMdmml6t0Njp",
	"g1pieW/Fe3QktpGY1kCweWqmo/bvcf3LqlVX99r/HtOAa9wCreTaYj4/hVAxTOGSzrwELmhxLZQvA4Mm",
	"N1IzPluoCVxuF/9uKdMhv5xBwYyhgjN5e8Yvp35BDw2S7xPAAEssmfp2u0UHMOJyp69Q0RIFQhUGa1SO",
	"ydB44Sgd8xEr2XBsqxwu/bd7JPUVkidqJZSwFfLRzfpncROuFV7OvJ8Jwhe2LQq0druCRLdqpUylEtf6",
	"+4d0MZUdrcHkuJhaLkPpvZtVZIAley5QDmriuyJXUj0P1p09rNJttnnzQb30vmex+YQGQpdrulCyb4Np",
	"OZk888YzeJeWxKRBClD+LurOwvgR5fBuZts0492LX9K9H5HNKmT8AAx6cJsiyI7J0Xi+Caixx/kr4YIt",
	"dwFq0LMeQS6frGbbLu/kjoDsw1sUaSUxaEK9eEwTKrQvOiLzrfg7cvZ1e+uxwEp3HWVWeOAR73vfa25E",
	"qeEXgcJQRvTJrb+YKYWr2uW00PWR0XwdPtpvOsRijIqbWvyJplOOBTa4CSIQ17UAbWz5xUpuQgl6obZd",
	"mByQFZWv6zbh9poL64Qq3D2l4EI9CaVe9yaHruIDyThHk4PPiRNf9z2dQm/8vs8YKUbuL90XyjrTFgTZ",
	"Obx58xYIF0HBpPREKR4TVig9feMgIB69RgNzNGs0kzk9OKWkZ6cLtVAXZNJcF23t82C8wxeqlAjx1lWv",
	"wJnWVT6f0OsfLi7OfdudENQUqCR+rWHJiitUfKG2Yg2ox0TIvGnQBrQlHKwFA80aMSk0xxLVtyErGN/U",
	"TlUjnF2oyIhf1KCidX47r/kp/KTB6NYh2Eo01gtLtw4Y2AYLaBtCtLASxrqQNKQoUFlMjO/t2UVwNA95",
	"slnfQYeTs0mjr/tuBoma7CNyMjCqaQ91xgzx5Pws6SDNsuPps+kxHRo5ymbZF/6R75NX3o2P1s+OogH7",
	"Vo22I82iV+iKKqZVMu0nRWV0jbzxCpufn9gcCk31Lf0PODPw8DTvcHBY7W1xoZotQsu96ooOptsepvvn",
	"fbyDcP9rW+mHRZKSBIRdKNpbqKZ1SeNdaBWUQTG8T7DdHTDtkIWAg9Z9p/ldt9mPu8XeuWW+HQY2qmp3",
	"50WeHx//n50+6G7v36PT620+iciJsNLGTzt8GSgZO6Cn+CgZb6Elz5/fv2RsesCv/eb+tbsTGLd59uIh",
	"ZA4nXvyq53/1yIJjpkQHlqRe6FZyP12yRFh5n+JAoZsZi92wQh8fohWNZJUwDEXBh3Ztgq59aGClDd0/",
	"JjdW2OwDbUkuHm5Qjz4KfnvYzd/7pqr1G/vwvK0UGD39cf4r9BLIyc8VZ1Ir3F7AsngFu1BdeLoghfur",
	"2Hgt20bXpJga72tPzs98lgkpqWYcvwWt5Ka7yCUP7xLVmEuHe+ctrMsHc2u/jXVYB+No025CjMLidj7M",
	"A5Ch46YTM/ddon/4PNFlOEDwFweXwQ3/AZPfu63/5MBy/OX9S/rhsU+MCgOfC+wBmfTW9vUK2HDeMDZu",
	"u+mxYAipAwYRbN2vAxuHfe/1DlLcYkM6j8xZSt/pJpzoByQTjNihwTzBaMFlSoPWkveOgDOfUsPHgDWV",
	"GkmjI7QtLLTKCQlsofp6OVTf8ESbrph+Gj4OG/ZVHrxORGaBSav96JnANYWEhWIrh+aaGW497Hp9egGJ",
	"rIh1H6/GHL6T1i/pPeaOz49ZwfaTo51Z1s/lrbtzEp/kr37gxMt4EvT1CDSQ9K7GZzNDfyragV4NjCDU",
	"VXYKp2R28/kpXHLm2OwSqBDzCJ0JZclhFopi/AQVwW2e7jI0NMVtZ79FOGMVhm2CXQVtJxOOv062djQZ",
	"a6LT5oID4cdSdZWJsInH5sH4MIxadP4be2/ZY0L67f9vhDRen+yXrml0erLtYz5NQ2DSDtsNg71rE4El",
	"ehPf9W+XNMn2XPsz5erPlDPTdt94xkySCwVwCsVbCU//nlToaz4PPnEtdGvlZtsrSAqsezQeZjL+PKjo",
	"MF3yssLiKvuMKhgMsYwVRWjWoqBSMk6RhGLoxfEXfwcJ3fBJANTJFIugfMzWTEiKEbsFwxuxRuXTva8R",
	"GBf+H5U1g+pAN74w8EO7BArGIPIbXTDZDeLG4dZtt2x2dCTpg0pbN/v6+Ovj7Dbfn8H1RQvZ9JNXcjMV",
	"+ulex62LKbprYUxYI6YruZlyXPuUHGneu2nzl15p52CT1ElUFk23oaGvhvaJ7GNcLKsInBwMdcmWZdrB",
	"3900gkjKb9qiGg5oxA0iQNxf/K5zDyYpVzZaEFTbLiTl3X64/Z8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
