// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AudiencePricePosition.
const (
	Budget    AudiencePricePosition = "budget"
	MidMarket AudiencePricePosition = "mid_market"
	Premium   AudiencePricePosition = "premium"
)

// Valid indicates whether the value is a known member of the AudiencePricePosition enum.
func (e AudiencePricePosition) Valid() bool {
	switch e {
	case Budget:
		return true
	case MidMarket:
		return true
	case Premium:
		return true
	default:
		return false
	}
}

// Defines values for AudienceSophistication.
const (
	High   AudienceSophistication = "high"
	Low    AudienceSophistication = "low"
	Medium AudienceSophistication = "medium"
)

// Valid indicates whether the value is a known member of the AudienceSophistication enum.
func (e AudienceSophistication) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for ExportRequestFormat.
const (
	ExportRequestFormatHtml   ExportRequestFormat = "html"
	ExportRequestFormatJsx    ExportRequestFormat = "jsx"
	ExportRequestFormatStripe ExportRequestFormat = "stripe"
)

// Valid indicates whether the value is a known member of the ExportRequestFormat enum.
func (e ExportRequestFormat) Valid() bool {
	switch e {
	case ExportRequestFormatHtml:
		return true
	case ExportRequestFormatJsx:
		return true
	case ExportRequestFormatStripe:
		return true
	default:
		return false
	}
}

// Defines values for ExportResultFormat.
const (
	ExportResultFormatHtml   ExportResultFormat = "html"
	ExportResultFormatJsx    ExportResultFormat = "jsx"
	ExportResultFormatStripe ExportResultFormat = "stripe"
)

// Valid indicates whether the value is a known member of the ExportResultFormat enum.
func (e ExportResultFormat) Valid() bool {
	switch e {
	case ExportResultFormatHtml:
		return true
	case ExportResultFormatJsx:
		return true
	case ExportResultFormatStripe:
		return true
	default:
		return false
	}
}

// Defines values for GenerationStatus.
const (
	Completed GenerationStatus = "completed"
	Failed    GenerationStatus = "failed"
	Pending   GenerationStatus = "pending"
	Streaming GenerationStatus = "streaming"
)

// Valid indicates whether the value is a known member of the GenerationStatus enum.
func (e GenerationStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case Pending:
		return true
	case Streaming:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusChecks.
const (
	HealthStatusChecksFail    HealthStatusChecks = "fail"
	HealthStatusChecksOk      HealthStatusChecks = "ok"
	HealthStatusChecksSkipped HealthStatusChecks = "skipped"
)

// Valid indicates whether the value is a known member of the HealthStatusChecks enum.
func (e HealthStatusChecks) Valid() bool {
	switch e {
	case HealthStatusChecksFail:
		return true
	case HealthStatusChecksOk:
		return true
	case HealthStatusChecksSkipped:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded HealthStatusStatus = "degraded"
	HealthStatusStatusOk       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusDegraded:
		return true
	case HealthStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PriceInterval.
const (
	Monthly PriceInterval = "monthly"
	OneTime PriceInterval = "one_time"
	Yearly  PriceInterval = "yearly"
)

// Valid indicates whether the value is a known member of the PriceInterval enum.
func (e PriceInterval) Valid() bool {
	switch e {
	case Monthly:
		return true
	case OneTime:
		return true
	case Yearly:
		return true
	default:
		return false
	}
}

// Defines values for PricingStrategy.
const (
	Anchor     PricingStrategy = "anchor"
	Freemium   PricingStrategy = "freemium"
	ValueBased PricingStrategy = "value_based"
)

// Valid indicates whether the value is a known member of the PricingStrategy enum.
func (e PricingStrategy) Valid() bool {
	switch e {
	case Anchor:
		return true
	case Freemium:
		return true
	case ValueBased:
		return true
	default:
		return false
	}
}

// Defines values for SiteProfileSourceType.
const (
	Spa    SiteProfileSourceType = "spa"
	Static SiteProfileSourceType = "static"
)

// Valid indicates whether the value is a known member of the SiteProfileSourceType enum.
func (e SiteProfileSourceType) Valid() bool {
	switch e {
	case Spa:
		return true
	case Static:
		return true
	default:
		return false
	}
}

// Defines values for StreamChunkType.
const (
	Done               StreamChunkType = "done"
	Error              StreamChunkType = "error"
	GenerationStarted  StreamChunkType = "generation_started"
	Token              StreamChunkType = "token"
	VariationCompleted StreamChunkType = "variation_completed"
	VariationStarted   StreamChunkType = "variation_started"
)

// Valid indicates whether the value is a known member of the StreamChunkType enum.
func (e StreamChunkType) Valid() bool {
	switch e {
	case Done:
		return true
	case Error:
		return true
	case GenerationStarted:
		return true
	case Token:
		return true
	case VariationCompleted:
		return true
	case VariationStarted:
		return true
	default:
		return false
	}
}

// AnalyzeRequest defines model for AnalyzeRequest.
type AnalyzeRequest struct {
	// Url The product URL to analyze.
	Url string `json:"url"`
}

// Audience defines model for Audience.
type Audience struct {
	PricePosition *AudiencePricePosition `json:"pricePosition,omitempty"`

	// Segment e.g. "SaaS founders", "enterprise IT", "indie developers".
	Segment string `json:"segment"`

	// Sophistication Price/technical sophistication of the audience.
	Sophistication AudienceSophistication `json:"sophistication"`
}

// AudiencePricePosition defines model for Audience.PricePosition.
type AudiencePricePosition string

// AudienceSophistication Price/technical sophistication of the audience.
type AudienceSophistication string

// ExportRequest defines model for ExportRequest.
type ExportRequest struct {
	Format      ExportRequestFormat `json:"format"`
	VariationId openapi_types.UUID  `json:"variationId"`
}

// ExportRequestFormat defines model for ExportRequest.Format.
type ExportRequestFormat string

// ExportResult defines model for ExportResult.
type ExportResult struct {
	// Content The exported artifact as text (JSX, HTML, or Stripe config JSON).
	Content string `json:"content"`

	// ContentType MIME type of the content, e.g. "text/plain".
	ContentType string `json:"contentType"`

	// Filename Suggested filename, e.g. "PricingSection.tsx".
	Filename string             `json:"filename"`
	Format   ExportResultFormat `json:"format"`
}

// ExportResultFormat defines model for ExportResult.Format.
type ExportResultFormat string

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Currency ISO 4217 currency code for generated prices.
	Currency    *string     `json:"currency,omitempty"`
	SiteProfile SiteProfile `json:"siteProfile"`

	// Strategies Strategies to generate. Defaults to all three when omitted. Duplicates are
	// rejected.
	Strategies *[]PricingStrategy `json:"strategies,omitempty"`
}

// Generation defines model for Generation.
type Generation struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	SiteProfile *SiteProfile       `json:"siteProfile,omitempty"`
	SourceUrl   string             `json:"sourceUrl"`
	Status      GenerationStatus   `json:"status"`
	Variations  []Variation        `json:"variations"`
}

// GenerationStatus defines model for Generation.Status.
type GenerationStatus string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Checks Per-dependency health, keyed by dependency name.
	Checks *map[string]HealthStatusChecks `json:"checks,omitempty"`
	Status HealthStatusStatus             `json:"status"`

	// Version Build version or git SHA.
	Version string `json:"version"`
}

// HealthStatusChecks defines model for HealthStatus.Checks.
type HealthStatusChecks string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Price defines model for Price.
type Price struct {
	// Amount Amount in the currency's minor unit (e.g. cents). 0 means free.
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`

	// CustomLabel Overrides the rendered price, e.g. "Contact us".
	CustomLabel *string       `json:"customLabel,omitempty"`
	Interval    PriceInterval `json:"interval"`
}

// PriceInterval defines model for Price.Interval.
type PriceInterval string

// PricingStrategy The psychological pricing strategy applied to a variation.
type PricingStrategy string

// PricingTier defines model for PricingTier.
type PricingTier struct {
	// Badge Optional badge text, e.g. "Most popular".
	Badge *string `json:"badge,omitempty"`

	// Cta Call-to-action label, e.g. "Start free".
	Cta      *string  `json:"cta,omitempty"`
	Features []string `json:"features"`

	// Highlighted Whether this tier is visually emphasized as the recommended plan.
	Highlighted *bool `json:"highlighted,omitempty"`

	// Name e.g. "Free", "Pro", "Enterprise".
	Name    string  `json:"name"`
	Price   Price   `json:"price"`
	Tagline *string `json:"tagline,omitempty"`
}

// Problem RFC 7807 problem details.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`

	// TraceId Correlation id for logs and traces.
	TraceId              *string                `json:"traceId,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SiteProfile defines model for SiteProfile.
type SiteProfile struct {
	AnalyzedAt time.Time `json:"analyzedAt"`
	Audience   Audience  `json:"audience"`

	// Industry Classified industry, e.g. "developer-tools", "e-commerce".
	Industry string `json:"industry"`

	// Keywords Salient terms extracted from the page.
	Keywords *[]string `json:"keywords,omitempty"`

	// SourceType Which scraper handled the page.
	SourceType SiteProfileSourceType `json:"sourceType"`
	Title      string                `json:"title"`
	Url        string                `json:"url"`

	// ValueProposition One-to-two sentence summary of what the product offers.
	ValueProposition string `json:"valueProposition"`
}

// SiteProfileSourceType Which scraper handled the page.
type SiteProfileSourceType string

// StreamChunk One event in the generation SSE stream. `type` discriminates the payload:
// - `generation_started`: carries `generationId`.
// - `variation_started`: a variation began; carries `strategy`.
// - `token`: an incremental text delta for a variation; carries `strategy`, `delta`.
// - `variation_completed`: a finished variation; carries `variation`.
// - `done`: terminal success; carries the full `generation`.
// - `error`: terminal failure; carries `problem`.
type StreamChunk struct {
	Delta        *string             `json:"delta,omitempty"`
	Generation   *Generation         `json:"generation,omitempty"`
	GenerationId *openapi_types.UUID `json:"generationId,omitempty"`

	// Problem RFC 7807 problem details.
	Problem *Problem `json:"problem,omitempty"`

	// Strategy The psychological pricing strategy applied to a variation.
	Strategy  *PricingStrategy `json:"strategy,omitempty"`
	Type      StreamChunkType  `json:"type"`
	Variation *Variation       `json:"variation,omitempty"`
}

// StreamChunkType defines model for StreamChunk.Type.
type StreamChunkType string

// Variation defines model for Variation.
type Variation struct {
	Headline string             `json:"headline"`
	Id       openapi_types.UUID `json:"id"`

	// Rationale Why this strategy fits the analyzed audience.
	Rationale *string `json:"rationale,omitempty"`

	// Strategy The psychological pricing strategy applied to a variation.
	Strategy    PricingStrategy `json:"strategy"`
	Subheadline *string         `json:"subheadline,omitempty"`
	Tiers       []PricingTier   `json:"tiers"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest RFC 7807 problem details.
type BadRequest = Problem

// Conflict RFC 7807 problem details.
type Conflict = Problem

// InternalError RFC 7807 problem details.
type InternalError = Problem

// NotFound RFC 7807 problem details.
type NotFound = Problem

// TooManyRequests RFC 7807 problem details.
type TooManyRequests = Problem

// UnprocessableEntity RFC 7807 problem details.
type UnprocessableEntity = Problem

// GenerateVariationsParams defines parameters for GenerateVariations.
type GenerateVariationsParams struct {
	// IdempotencyKey Client-supplied key to make generation idempotent. Repeating a request with the
	// same key once the first has completed returns the same generation instead of
	// producing a new one. A repeat request with the same key while the first is still
	// in progress gets 409 Conflict instead of starting a second, redundant generation.
	//
	// Omitting this header does not disable deduplication: the server derives an
	// implicit key from the request's siteProfile, strategies, and currency, so two
	// requests with identical content are deduplicated the same way even without a
	// shared client-chosen key. A practical consequence: two different callers
	// submitting the same public product URL with the same strategies can transparently
	// receive the same generation, or a 409 if the first is still running, even though
	// neither supplied an Idempotency-Key. See ADR-0010.
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// AnalyzeSiteJSONRequestBody defines body for AnalyzeSite for application/json ContentType.
type AnalyzeSiteJSONRequestBody = AnalyzeRequest

// ExportVariationJSONRequestBody defines body for ExportVariation for application/json ContentType.
type ExportVariationJSONRequestBody = ExportRequest

// GenerateVariationsJSONRequestBody defines body for GenerateVariations for application/json ContentType.
type GenerateVariationsJSONRequestBody = GenerateRequest

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["traceId"]; found {
		err = json.Unmarshal(raw, &a.TraceId)
		if err != nil {
			return fmt.Errorf("error reading 'traceId': %w", err)
		}
		delete(object, "traceId")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	if a.TraceId != nil {
		object["traceId"], err = json.Marshal(a.TraceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traceId': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Analyze a product URL and return a site profile.
	// (POST /v1/analyze)
	AnalyzeSite(w http.ResponseWriter, r *http.Request)
	// Export one variation of a generation in the requested format.
	// (POST /v1/export/{id})
	ExportVariation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Generate three pricing-page variations (SSE stream).
	// (POST /v1/generate)
	GenerateVariations(w http.ResponseWriter, r *http.Request, params GenerateVariationsParams)
	// Fetch a previously produced generation.
	// (GET /v1/generations/{id})
	GetGeneration(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Liveness and readiness probe.
	// (GET /v1/healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Analyze a product URL and return a site profile.
// (POST /v1/analyze)
func (_ Unimplemented) AnalyzeSite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Export one variation of a generation in the requested format.
// (POST /v1/export/{id})
func (_ Unimplemented) ExportVariation(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate three pricing-page variations (SSE stream).
// (POST /v1/generate)
func (_ Unimplemented) GenerateVariations(w http.ResponseWriter, r *http.Request, params GenerateVariationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a previously produced generation.
// (GET /v1/generations/{id})
func (_ Unimplemented) GetGeneration(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness and readiness probe.
// (GET /v1/healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AnalyzeSite operation middleware
func (siw *ServerInterfaceWrapper) AnalyzeSite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzeSite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportVariation operation middleware
func (siw *ServerInterfaceWrapper) ExportVariation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportVariation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateVariations operation middleware
func (siw *ServerInterfaceWrapper) GenerateVariations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GenerateVariationsParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateVariations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGeneration operation middleware
func (siw *ServerInterfaceWrapper) GetGeneration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGeneration(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/analyze", wrapper.AnalyzeSite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/export/{id}", wrapper.ExportVariation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/generate", wrapper.GenerateVariations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/generations/{id}", wrapper.GetGeneration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/healthz", wrapper.HealthCheck)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fvrcty2kn6VLu6pOnYtZyQ7cSWZ/FIcJ1GOHbs8yqU2440homeICAR4AFDSxKV33+oGL+AMRxfvJqn9",
	"pyEJoIHu/vrrRutDVtiqtgZN8NniQ1YLJyoM6PjXqcSqtgFNsf0XbumJRF84VQdlTbbInmuFJsx8U9da",
	"oYQL3EKwUIkLhA0adII+BNVNE+bwFmsUQZkNCHD47wZ9gCsVSgglrowXFfIs1hRIj2CtnA9QCg8kqMaA",
	"EhyGxhnP73lEupbxAYUEu16Z2lnZFHEtg1dgDc7hBByLsLc69ItflUqnqysPPiitV0YZqJ3dOPQeNhg8",
	"fHr8BTy3Zq1VEZK1wQfh2l16LKyROTiUjZHChETc+cqszOtKBf42lMpDiUKiA2nRg7EBpPLiXCNIlE2t",
	"VcHjFlFgdJf0KTp1iR6EWRlV0Tcq8D7Wzlb8YbvVf3rwKuAbZ9dKYw4+OBFwo9DnIIyEonGOdJ2DtxCu",
	"7Mq0A308JCXRBFUIDYU1pE4QLhUM5XCOV2ILeImGR9omgFgZXwqHEopoNUVpPRoSlJRSO1H0c3ta1hS4",
	"IClAqvUaHS1XCK3R+ZXxzflwaO2KdXOuVQFR6QF+fPtyR7XDdqEQBoITxteCJtZb2mqB6hKnjCoH60Cw",
	"rtV6wi7ANcYos8njjmm/m3JlDKpQooPePYSBxKNm/6KdLxHh5Ou3s+PjJ8fzlcnyTJFnRSvI8syICrNF",
	"tjMuyzNflFgJ8slKXL9Eswlltnj67FmeVcp0vz/Ps7CtaQIfnDKb7ObmJs8c+poOmX38KyHfRi3Tr1ax",
	"9Keoe3M7qp0911j95++e/P5Dsvg/HK6zRfYfRwOOHMW3/uhNHBUXHSPH2WCVcCU8VEKvratQzrObPOs8",
	"6q+U6CRFkbHh7Bw+6V1oh0JuIQGEOfwsVIC1daACBLsya2WUL3OayBBoue0E2ARLSAIqeHDoGx3Y2hqP",
	"LWi13zCgrIww0BiHmp1thCN0bqcmoDNCv3DOur/08EgsvK6xILmQlgdbMJ5Ejf5gwze2MfJvsjEOGt42",
	"rsABWfFa+cDSnVn7Spht6wf+rxTyrQgIWlWK5CkQJR1Y3vo/S/KWDGd2sg7o9iPwkoOLJwu5Ius7x7V1",
	"GI1Nmc18DBTKqKqpssVxDwvKBNygI8lu8uxHCpkFeo44L0xQYft3gsIVaj2LsADnTQCPlYgBSJPnXQqt",
	"yLpuuj3ycZ0Yobd/YIJpQkpFKwj9xtkaXVCEfGuhPeZZnTz6kDVO758xiZVGlWBBxEXoePFaEC/x2eLX",
	"rAyh9oujo/bZvLBV9i7PaAsiZIuscSrbR2QC5H83yqGkOUiEd/1H9vx3LALZ6EkjFcXEB+6odqrAN9ar",
	"uJkPGRqygF+z80ZuMGQULuRvlXAX/KN2WKmmSiToxMwzj5uqNYPxAeF8M4dVthRiCWvycorRWQ6rDAmQ",
	"aqc8wulZfKSMVEQaLlGTnH6VzbOpxWxdKh9aW9tf8w3t6yhgURpmDePviYIRyor20FhR7ca1vaJdo6R9",
	"5lmpNuXEdne00u19T7ApVb24rq0LH2eBna0MivrdX5OYodK0enCqxkn1XAqnWKZTmU6UNY2Sd1pdOrg3",
	"2Nv2RpHqgVtLYGTfwZDnJZLkglqLIoDwEPA6wKPvl7/k8N3Zq5ccGZd8AsQS12oD3y9f//B40oDa1c74",
	"+e6Kr05fvQAa0hlK+3UOrS3Tyke1FsocsE9i0JGb7UFys9nEkNN9089KRqvMZokFB+3grw/N/pFWsKPV",
	"dppE2vG59L8mVf1tpBcfCaVdMhEPaC3YXrIfl19nu7B/unwNnz598lmff0BhJTKRahkOSmAc83RYtQjE",
	"crJF9t+/nsz+692HT27+MYkgQ6pzV0xaJp/e8PG2icKEdockgplblG8OX8ct8lOhNYTSIcIVMT9LqQrK",
	"OXzd5UmeEidKOX5nwtTy/oCVvzt6RguKUmxJ2kpcn8ahnzD3b3886Y9EOCe2+4iW7PkW7bfg+xDFOySN",
	"nYQRCkkRcBYUm+CeqtR9EOt/pVGmfj/G6H57OCb1i9D41PlqNJJesmmgqOLffUGCHEwojfJ2XOYp76Xl",
	"n7ohNP5WLfJBDbvrhR8tmyc6mVL1dyh0KJf9th+i7BKLi1sGDWdoL9pjIiEvVF0fOK6dMI9uJpHOn4Gh",
	"ZElzSoqIE24heUf4loDpsL19fbIsEjdOyENKQ+cnecdXjdIS2tcUjzYqwPK7k/mdIXbQTDv3lCqY1jxQ",
	"B6KyzVRYPeHnlKJyhGvB9Z8eKmUoxTQqwCOOTAVZ3+M5HEOFwnhYO+SjvC1hyEcIf19QLhofbPVSnOME",
	"0X59ic4pib4tWhGR7KC/j6HPrQlED5pDzJEkdJdCjxRu8LcWfCprQqm3WZ5tUTi9vTuKtuebbDhZ5JAS",
	"U5Cezij8tiitthumr3Uc0tWotiDamhGFE+h9OeWxwhSldeRUDiNpJ6fXDf52LvwBs24lO1Mxl3yAkZ0L",
	"uZkgO6/rOB74PRO2XlOvrA9Q27rRwh3QVRHERFVZaD0LdiaYJYEmY+knXQbhAhvoIeqEIjQOx2C799UY",
	"VGMWoNWmJDRPCUt7FmMBfy6RC3tcrw0KHSgPl8o3nJhiVZfCqz+Iy3aWXNiqInOWUGthErnPrdUoGOen",
	"2WS77W94wzlzSBv/eNHnVgdOou6w5C5CwSEyiI1WBidOa8cdWh4ZZ0/Oe9oTYrJ/0NaCa/aO9+03z+Gz",
	"z48/g7bAABKDUDqSv5FRxheTClbGB9Gmy7dE+EpcR4R79sUXCd49OZ5EvKCCnp4xOFHgqZwwZuu4XBfv",
	"QZjUarvxXG/nQX5Sd6FPWzrmLM5tExbnWpiL7IElhSh2v+0pRS3H1Ooh0SeWQh7E90RSy7jNOPuaBytU",
	"Nj64yVso4b1aE1p2H/Vw0dcZZsFa3VUlZuyPrjjkORe4vbJOTtF/wZcXENBVHvCaVMipXnfVUosNh877",
	"Q09kb9N56s+lKkrwhRM1OiiFkbq9ZOnW6aKBr0WrYVVMQv9h223uR4s5tpA5JMWknWBgkHA7XFnwSHll",
	"geCbqhJuS3n2VSlClL0tptn1Gp2f36sklvdWvCdHYhuJaY0ONk/NdNL+mdc/Lxtzcaf9722ar316opVc",
	"IyyXLyBmDHN4T2u+B6locKUMp4FRk1tthVyszAzeD4N/44o/yvcLKIRzlHAmb0/l+zkP6KlB8n1CGOAc",
	"N8J8OUzREYx2eLAXaGiIAWUKhxWaIHQsvEjUQTBiJRNOTZXDe/52T6Q+Q2Kh4nUIysnJ+mftJNIafL9g",
	"P1PEL3xTFOj9MIKv4Rqt01Npx/L9QzqY0o7GYbJcG1rex9R7N6roSEv2XGAzyolvQ64kex6NO71fplsP",
	"cfNetfS+ZrH9iAJCF2s6KNm3wTSdTJ6x8YzepSkxaZAAiu+ibk2MH5AO70a2bT1dvfgpnfsB0axEIQ/Q",
	"oHuXKeLZCT2J59vIGnuev1Yh2nIHUKOa9QRz+Wg1++b81t0Rkb1/iSLNJEZFqGcPKULF8kUnZD4cfyfO",
	"vm5vmAusbVdRFvGauL0nf2ulUxsLPylUjiIiB7f+YmajQtmczwtbHTkrL+NH+0WHNhmj5KZSf6DrlONB",
	"jG6CiMR1JUDflvzaTG5GAXplhipMDiiKkvO6bWwMkcoHZYpwRyq4Mo9iqte9yaHL+EALKdHlwDFxxnnf",
	"4zn0xs91xlZilHz5vDI+uKYgyi7h5ctXQLyIGytYKCPbgBVTTy4cRMZjL9HBkjtOZkt68IKCnucOljMy",
	"aWmLpuI42HbmKLPRCO2tq11DcE0oOZ7Q6+/Ozt5w2Z0Y1BwoJf7WwrkoLtDIlRmONbIe11LmbY0+si0V",
	"4FIJsKJWs8JK3KD5MkYFx0XtVDUq+JVpN8KDajQ0jqdjzc/hBwvONgHBl6r2Q98K+BoLaGpitLHxIwYN",
	"rQo0HhPje3V6Fh2NKU+26CvocHI6q+1VX82goyb7aHcyMqp5T3WmDPHkzWlSQVpkx/Mn82NatN1Rtsg+",
	"4UdcJy/ZjY8unxy1BsylGusnikXfYCjKNqySaT8qSmcrlDUrbPnmxOdQWMpv6XfkmXEPj/OOB8fRbIvc",
	"fNUxtLa7qKPpvqfp/LzHO4j3v77R3NiTpCSg/MrQ3MrUTUgK723rA29/CLDdHTDNkEXAQR++svK22+yH",
	"3WLv3DLfjIGNstrdPpunx8f/Z6uPqtv79+j0eognLXMirrTlbodPoyRTC/QSHyVtQTTk6dO7h0x1D/DY",
	"L+4eu9uBcZNnz+4j5rjjhUc9/atbFoJwGwzcWgeFbbTk7pJzhDX7lASCbuE8ds0KPT60VjQRVWKLI4EP",
	"zVpHXTM0iI2P1T+ht1757B1NSS4eb1CPPih5c9jN33JR1fPEDM9DpiDo6ffLX6A/gZz83EihrcHhAla0",
	"V7Ar08HTGTcofr98/UN7Ldu0rkmY2t7Xnrw55SgTQ1IlJH4J1uhtd5FLHt4FqimXjvfOA63LR62qv05V",
	"WEcdqPOus45gceirYwIydty0Y+auS/R3fw66jBsI/mJwGd3wHzD5vdv6jwaW40/vHtI3j30kKox8Lm4P",
	"yKQH27drEOMu4rRvFrluV4mQOmA8gsH9OrJx2Pe+3WGKAzfkNkLhhNZc6SaeyI2CCUfs2GCecLToMrEb",
	"WfgpcsYhNX4MWFGqkRQ6YtnCQ2OC0iBWps+XY/YNj6zrkunH8eM44dCJ/W1yZB6E9pZbzxReEiSsjFgH",
	"dFfCSc+069sXZ5CcFW2d8WrK4bvT+im9x9zx+SkrGD452mlf/7O8dbdP4qP8lRtO+IxnUV8PYANJ7Wq6",
	"NzPWp1o7sOuREcS8ys/hBZndcvkC3ksRxOI9UCLGDF0o48lhVoYwfoaG6LZMZxkbmpG+s98irrGOzTbR",
	"rqK2kw7HX2aDHc2miug0uZJA/HFjusxE+VGLNhsfxlaLzn/b2lv2EEi/+VgguwfL6fua/x9RqumEZj/X",
	"TeHs0VD4fJxiZlI/28XNHgtIwA2yT+wCQkiqantY8CcF9z8pyKb1wekQm0QjQnzC7uGE539P7OQkkdkq",
	"XirbeL0digtJRnaHxmMTxx8HFR3bUZ6XWFxkf6IKRl0vU1kUuktVUO7Ztp3E7OnZ8Sd/hwhdt0pk4Enb",
	"i6IALi6F0oQRuxnGS3WJhvkBJxVCKv5FedAonbA1ZxLc5UssYopTv7SF0F3nbtsNO5TXFkdHmj4orQ+L",
	"z48/P+Z4286/d43GN1ppWWCbJEGU88wHN+5TnZv8EKXqciZiHgdhKZlyk5bndydtGSIFL/4PpVH3RTtB",
	"y/72B7/uTFloCoS1VcTDhoF00Dfvbv4nAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
