// Code generated by MockGen. DO NOT EDIT.
// Source: redis_idempotency_store.go
//
// Generated by this command:
//
//	mockgen -source=redis_idempotency_store.go -destination=../../../test/mocks/cache/redis_get_setter_mock.go -package=mockcache
//

// Package mockcache is a generated GoMock package.
package mockcache

import (
	context "context"
	reflect "reflect"
	time "time"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockredisGetSetter is a mock of redisGetSetter interface.
type MockredisGetSetter struct {
	ctrl     *gomock.Controller
	recorder *MockredisGetSetterMockRecorder
	isgomock struct{}
}

// MockredisGetSetterMockRecorder is the mock recorder for MockredisGetSetter.
type MockredisGetSetterMockRecorder struct {
	mock *MockredisGetSetter
}

// NewMockredisGetSetter creates a new mock instance.
func NewMockredisGetSetter(ctrl *gomock.Controller) *MockredisGetSetter {
	mock := &MockredisGetSetter{ctrl: ctrl}
	mock.recorder = &MockredisGetSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockredisGetSetter) EXPECT() *MockredisGetSetterMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockredisGetSetter) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(*redis.IntCmd)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockredisGetSetterMockRecorder) Del(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockredisGetSetter)(nil).Del), varargs...)
}

// Get mocks base method.
func (m *MockredisGetSetter) Get(ctx context.Context, key string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockredisGetSetterMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockredisGetSetter)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockredisGetSetter) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockredisGetSetterMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockredisGetSetter)(nil).Set), ctx, key, value, expiration)
}

// SetNX mocks base method.
func (m *MockredisGetSetter) SetNX(ctx context.Context, key string, value any, expiration time.Duration) *redis.BoolCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value, expiration)
	ret0, _ := ret[0].(*redis.BoolCmd)
	return ret0
}

// SetNX indicates an expected call of SetNX.
func (mr *MockredisGetSetterMockRecorder) SetNX(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockredisGetSetter)(nil).SetNX), ctx, key, value, expiration)
}
