// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/redis/go-redis/v9 (interfaces: Scripter)
//
// Generated by this command:
//
//	mockgen -destination=../../../test/mocks/cache/redis_scripter_mock.go -package=mockcache github.com/redis/go-redis/v9 Scripter
//

// Package mockcache is a generated GoMock package.
package mockcache

import (
	context "context"
	reflect "reflect"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockScripter is a mock of Scripter interface.
type MockScripter struct {
	ctrl     *gomock.Controller
	recorder *MockScripterMockRecorder
	isgomock struct{}
}

// MockScripterMockRecorder is the mock recorder for MockScripter.
type MockScripterMockRecorder struct {
	mock *MockScripter
}

// NewMockScripter creates a new mock instance.
func NewMockScripter(ctrl *gomock.Controller) *MockScripter {
	mock := &MockScripter{ctrl: ctrl}
	mock.recorder = &MockScripterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScripter) EXPECT() *MockScripterMockRecorder {
	return m.recorder
}

// Eval mocks base method.
func (m *MockScripter) Eval(ctx context.Context, script string, keys []string, args ...any) *redis.Cmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx, script, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Eval", varargs...)
	ret0, _ := ret[0].(*redis.Cmd)
	return ret0
}

// Eval indicates an expected call of Eval.
func (mr *MockScripterMockRecorder) Eval(ctx, script, keys any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, script, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eval", reflect.TypeOf((*MockScripter)(nil).Eval), varargs...)
}

// EvalRO mocks base method.
func (m *MockScripter) EvalRO(ctx context.Context, script string, keys []string, args ...any) *redis.Cmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx, script, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EvalRO", varargs...)
	ret0, _ := ret[0].(*redis.Cmd)
	return ret0
}

// EvalRO indicates an expected call of EvalRO.
func (mr *MockScripterMockRecorder) EvalRO(ctx, script, keys any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, script, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvalRO", reflect.TypeOf((*MockScripter)(nil).EvalRO), varargs...)
}

// EvalSha mocks base method.
func (m *MockScripter) EvalSha(ctx context.Context, sha1 string, keys []string, args ...any) *redis.Cmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sha1, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EvalSha", varargs...)
	ret0, _ := ret[0].(*redis.Cmd)
	return ret0
}

// EvalSha indicates an expected call of EvalSha.
func (mr *MockScripterMockRecorder) EvalSha(ctx, sha1, keys any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sha1, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvalSha", reflect.TypeOf((*MockScripter)(nil).EvalSha), varargs...)
}

// EvalShaRO mocks base method.
func (m *MockScripter) EvalShaRO(ctx context.Context, sha1 string, keys []string, args ...any) *redis.Cmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sha1, keys}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EvalShaRO", varargs...)
	ret0, _ := ret[0].(*redis.Cmd)
	return ret0
}

// EvalShaRO indicates an expected call of EvalShaRO.
func (mr *MockScripterMockRecorder) EvalShaRO(ctx, sha1, keys any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sha1, keys}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvalShaRO", reflect.TypeOf((*MockScripter)(nil).EvalShaRO), varargs...)
}

// ScriptExists mocks base method.
func (m *MockScripter) ScriptExists(ctx context.Context, hashes ...string) *redis.BoolSliceCmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range hashes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScriptExists", varargs...)
	ret0, _ := ret[0].(*redis.BoolSliceCmd)
	return ret0
}

// ScriptExists indicates an expected call of ScriptExists.
func (mr *MockScripterMockRecorder) ScriptExists(ctx any, hashes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, hashes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScriptExists", reflect.TypeOf((*MockScripter)(nil).ScriptExists), varargs...)
}

// ScriptLoad mocks base method.
func (m *MockScripter) ScriptLoad(ctx context.Context, script string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScriptLoad", ctx, script)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// ScriptLoad indicates an expected call of ScriptLoad.
func (mr *MockScripterMockRecorder) ScriptLoad(ctx, script any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScriptLoad", reflect.TypeOf((*MockScripter)(nil).ScriptLoad), ctx, script)
}
