// Code generated by MockGen. DO NOT EDIT.
// Source: redis_response_cache.go
//
// Generated by this command:
//
//	mockgen -source=redis_response_cache.go -destination=../../../test/mocks/cache/redis_cache_client_mock.go -package=mockcache
//

// Package mockcache is a generated GoMock package.
package mockcache

import (
	context "context"
	reflect "reflect"
	time "time"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockredisCacheClient is a mock of redisCacheClient interface.
type MockredisCacheClient struct {
	ctrl     *gomock.Controller
	recorder *MockredisCacheClientMockRecorder
	isgomock struct{}
}

// MockredisCacheClientMockRecorder is the mock recorder for MockredisCacheClient.
type MockredisCacheClientMockRecorder struct {
	mock *MockredisCacheClient
}

// NewMockredisCacheClient creates a new mock instance.
func NewMockredisCacheClient(ctrl *gomock.Controller) *MockredisCacheClient {
	mock := &MockredisCacheClient{ctrl: ctrl}
	mock.recorder = &MockredisCacheClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockredisCacheClient) EXPECT() *MockredisCacheClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockredisCacheClient) Get(ctx context.Context, key string) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockredisCacheClientMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockredisCacheClient)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockredisCacheClient) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(*redis.StatusCmd)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockredisCacheClientMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockredisCacheClient)(nil).Set), ctx, key, value, expiration)
}
