// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=../../test/mocks/domain/ports_mock.go -package=mockdomain
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodvieira/pricing-optimizer-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMProvider is a mock of LLMProvider interface.
type MockLLMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderMockRecorder
	isgomock struct{}
}

// MockLLMProviderMockRecorder is the mock recorder for MockLLMProvider.
type MockLLMProviderMockRecorder struct {
	mock *MockLLMProvider
}

// NewMockLLMProvider creates a new mock instance.
func NewMockLLMProvider(ctrl *gomock.Controller) *MockLLMProvider {
	mock := &MockLLMProvider{ctrl: ctrl}
	mock.recorder = &MockLLMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProvider) EXPECT() *MockLLMProviderMockRecorder {
	return m.recorder
}

// ClassifySite mocks base method.
func (m *MockLLMProvider) ClassifySite(ctx context.Context, page domain.ScrapedPage) (*domain.SiteProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassifySite", ctx, page)
	ret0, _ := ret[0].(*domain.SiteProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassifySite indicates an expected call of ClassifySite.
func (mr *MockLLMProviderMockRecorder) ClassifySite(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassifySite", reflect.TypeOf((*MockLLMProvider)(nil).ClassifySite), ctx, page)
}

// GenerateStructured mocks base method.
func (m *MockLLMProvider) GenerateStructured(ctx context.Context, in domain.GenerationInput) (*domain.Variation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStructured", ctx, in)
	ret0, _ := ret[0].(*domain.Variation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStructured indicates an expected call of GenerateStructured.
func (mr *MockLLMProviderMockRecorder) GenerateStructured(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStructured", reflect.TypeOf((*MockLLMProvider)(nil).GenerateStructured), ctx, in)
}

// StreamStructured mocks base method.
func (m *MockLLMProvider) StreamStructured(ctx context.Context, in domain.GenerationInput) (<-chan domain.StreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamStructured", ctx, in)
	ret0, _ := ret[0].(<-chan domain.StreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamStructured indicates an expected call of StreamStructured.
func (mr *MockLLMProviderMockRecorder) StreamStructured(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamStructured", reflect.TypeOf((*MockLLMProvider)(nil).StreamStructured), ctx, in)
}

// MockScraper is a mock of Scraper interface.
type MockScraper struct {
	ctrl     *gomock.Controller
	recorder *MockScraperMockRecorder
	isgomock struct{}
}

// MockScraperMockRecorder is the mock recorder for MockScraper.
type MockScraperMockRecorder struct {
	mock *MockScraper
}

// NewMockScraper creates a new mock instance.
func NewMockScraper(ctrl *gomock.Controller) *MockScraper {
	mock := &MockScraper{ctrl: ctrl}
	mock.recorder = &MockScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScraper) EXPECT() *MockScraperMockRecorder {
	return m.recorder
}

// Scrape mocks base method.
func (m *MockScraper) Scrape(ctx context.Context, url string) (*domain.ScrapedPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrape", ctx, url)
	ret0, _ := ret[0].(*domain.ScrapedPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scrape indicates an expected call of Scrape.
func (mr *MockScraperMockRecorder) Scrape(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrape", reflect.TypeOf((*MockScraper)(nil).Scrape), ctx, url)
}

// MockGenerationRepo is a mock of GenerationRepo interface.
type MockGenerationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGenerationRepoMockRecorder
	isgomock struct{}
}

// MockGenerationRepoMockRecorder is the mock recorder for MockGenerationRepo.
type MockGenerationRepoMockRecorder struct {
	mock *MockGenerationRepo
}

// NewMockGenerationRepo creates a new mock instance.
func NewMockGenerationRepo(ctrl *gomock.Controller) *MockGenerationRepo {
	mock := &MockGenerationRepo{ctrl: ctrl}
	mock.recorder = &MockGenerationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerationRepo) EXPECT() *MockGenerationRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGenerationRepo) Get(ctx context.Context, id string) (*domain.Generation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Generation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGenerationRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGenerationRepo)(nil).Get), ctx, id)
}

// Save mocks base method.
func (m *MockGenerationRepo) Save(ctx context.Context, g domain.Generation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGenerationRepoMockRecorder) Save(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGenerationRepo)(nil).Save), ctx, g)
}
