// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=../../test/mocks/domain/ports_mock.go -package=mockdomain
//

// Package mockdomain is a generated GoMock package.
package mockdomain

import (
	context "context"
	reflect "reflect"

	domain "github.com/rodvieira/pricing-optimizer-api/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMProvider is a mock of LLMProvider interface.
type MockLLMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderMockRecorder
	isgomock struct{}
}

// MockLLMProviderMockRecorder is the mock recorder for MockLLMProvider.
type MockLLMProviderMockRecorder struct {
	mock *MockLLMProvider
}

// NewMockLLMProvider creates a new mock instance.
func NewMockLLMProvider(ctrl *gomock.Controller) *MockLLMProvider {
	mock := &MockLLMProvider{ctrl: ctrl}
	mock.recorder = &MockLLMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProvider) EXPECT() *MockLLMProviderMockRecorder {
	return m.recorder
}

// GenerateStructured mocks base method.
func (m *MockLLMProvider) GenerateStructured(ctx context.Context, in domain.GenerationInput) (*domain.Variation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStructured", ctx, in)
	ret0, _ := ret[0].(*domain.Variation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateStructured indicates an expected call of GenerateStructured.
func (mr *MockLLMProviderMockRecorder) GenerateStructured(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStructured", reflect.TypeOf((*MockLLMProvider)(nil).GenerateStructured), ctx, in)
}

// StreamStructured mocks base method.
func (m *MockLLMProvider) StreamStructured(ctx context.Context, in domain.GenerationInput) (<-chan domain.StreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamStructured", ctx, in)
	ret0, _ := ret[0].(<-chan domain.StreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamStructured indicates an expected call of StreamStructured.
func (mr *MockLLMProviderMockRecorder) StreamStructured(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamStructured", reflect.TypeOf((*MockLLMProvider)(nil).StreamStructured), ctx, in)
}
